spring:
  #
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: testdatabase
  #
  shell:
    interactive:
      enabled: true
  #
  main:
    banner-mode: off

mongock:
  runner-type: "InitializingBean" # default
  change-logs-scan-package:
    - ru.cap.home.mongock.changelog.DBChangelog

logging:
  level:
    root: info
