spring:
  #
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: testdatabase
  #
  shell:
    interactive:
      enabled: true
  #
  main:
    banner-mode: off

logging:
  level:
    root: info

