select * from dual;
iNSERT INTO author VALUES(1, 'T. Draizer');
iNSERT INTO author VALUES(2, 'A. Pushkin');
iNSERT INTO author VALUES(3, 'M. Tven');
iNSERT INTO genre VALUES(1, 'Classic');
iNSERT INTO genre VALUES(2, 'Poem');
iNSERT INTO genre VALUES(3, 'Drama');
iNSERT INTO BOOK (AUTHOR_ID,GENRE_ID,TITLE) VALUES(1,1, 'Finansist');
iNSERT INTO BOOK (AUTHOR_ID,GENRE_ID,TITLE) VALUES(2,2, 'Time');
insert into comment(book_id, comment) values (1, 'Cool!');
insert into comment(book_id, comment) values (1, 'Best!');
insert into comment(book_id, comment) values (1, 'Exc!');
insert into comment(book_id, comment) values (2, 'Cool! v2');
insert into comment(book_id, comment) values (2, 'Best! v2');
insert into comment(book_id, comment) values (2, 'Exc! v2');