spring:
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  shell:
    interactive:
      enabled: false
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  level:
    root: info
