spring:
  application: name=hw-14-spring-batch

  datasource:
    url: jdbc:h2:mem:testdb
    username:
    password:

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    mongodb:
      database: spring-batch

app:
  csvPath: customers-1000.csv
  bathSize: 10
